# Generated by Django 4.0.6 on 2022-08-05 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 30, 32, 710600, tzinfo=utc)),
        ),
    ]
