# Generated by Django 4.0.6 on 2022-08-05 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 53, 35, 326868, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='FMY6BCMN68XCADI', editable=False, max_length=20),
        ),
    ]
