# Generated by Django 4.0.6 on 2022-08-05 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_published_datetime_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 54, 40, 115532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='22Y8OBCPYKIEZII', max_length=20),
        ),
    ]
