# Generated by Django 4.0.6 on 2022-08-05 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_published_datetime_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 59, 44, 540926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 59, 44, 540415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='JHEGC02HNLQ9BS4', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='GF4GX899RSIL5Y2', max_length=20),
        ),
    ]
