# Generated by Django 4.0.6 on 2022-08-06 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_reply_published_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 11, 45, 51, 748482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='HGM139YJ8CGWAA1', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 11, 45, 51, 750365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='KL7ZY16FL6X09TG', max_length=20),
        ),
    ]
