# Generated by Django 4.0.6 on 2022-08-08 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_published_datetime_alter_post_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='XETLQG905UY52SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 21, 50, 31, 474224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='VCJVWY57LFI3M8D', max_length=20),
        ),
    ]
