# Generated by Django 4.0.6 on 2022-08-08 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_published_datetime_alter_post_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='7DN4Z9L70WBS4Y1', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 21, 51, 45, 484966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='K3EGDRXCCPCDPYW', max_length=20),
        ),
    ]
