# Generated by Django 4.0.6 on 2022-08-13 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_url_alter_reply_published_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='4FXN6G89AHYBIM9', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='G2IRNQGHZAGZJWY', max_length=20),
        ),
    ]
