# Generated by Django 4.0.6 on 2022-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_post_url_alter_reply_published_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='L0YEXPM5GDK38KS', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='FYCP2RAWN3RPRN8', max_length=20),
        ),
    ]
