# Generated by Django 4.0.6 on 2022-08-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_url_alter_reply_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='I6GBI0V7EE438FR', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(default='Q2LT6CTZ2JF8MGQ', max_length=20),
        ),
    ]
