# Generated by Django 4.0.6 on 2022-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_url_alter_reply_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
