# Generated by Django 4.0.6 on 2022-08-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_url_alter_reply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='post_images'),
        ),
    ]
