# Generated by Django 4.0.6 on 2022-08-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userextended_savedposttext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='savedPostText',
            new_name='saved_post_text',
        ),
    ]
