# Generated by Django 4.0.6 on 2022-08-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_savedposttext_userextended_saved_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='profile_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
