# Generated by Django 4.0.6 on 2022-08-24 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_userextended_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='account_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='AccountConfirmationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
