# Generated by Django 4.0.6 on 2022-08-25 11:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userextended_account_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfirmationemail',
            name='expiration_date',
            field=models.DateTimeField(default=user.models.get_next_day),
        ),
    ]
