# Generated by Django 4.0.6 on 2022-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_resetpasswordemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='friends_list',
            field=models.ManyToManyField(to='user.userextended'),
        ),
    ]
