# Generated by Django 4.0.6 on 2022-08-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userextended_friends_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='friends_list',
            new_name='friends',
        ),
    ]
