# Generated by Django 4.0.6 on 2022-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_friends_list_userextended_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='received_friend_request',
            field=models.ManyToManyField(to='user.userextended'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='sent_friend_request',
            field=models.ManyToManyField(to='user.userextended'),
        ),
    ]
