# Generated by Django 4.0.6 on 2022-08-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_received_friend_request_userextended_received_friend_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='sent_friend_requess',
            new_name='sent_friend_requests',
        ),
    ]
