# Generated by Django 4.0.6 on 2022-08-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_sent_friend_requess_userextended_sent_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='received_friend_requests',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='sent_friend_requests',
        ),
    ]
