# Generated by Django 4.0.6 on 2022-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_userextended_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='bio',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
